version: '2'
services:
  covid19-app:
    image: covid19
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://covid19-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=Covid19
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  covid19-mongodb:
    extends:
      file: mongodb.yml
      service: covid19-mongodb
